In [7]:
# Numpyのアレイを利用
import numpy as np

list1 = [1,2,3,4]
np_array = np.array(list1)
np_array

array([1, 2, 3, 4])

In [10]:
list2 = [11,22,33,44]
lists = [list1, list2]
np_array = np.array(lists)
np_array

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [4]:
# アレイのサイズを調べる
np_array.shape

(2, 4)

In [5]:
# アレイのデータ型を調べる
np_array.dtype

dtype('int64')

In [8]:
# 特別なアレイを作る

#すべての要素が０
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
my_zeros_array = np.zeros(5)

In [10]:
my_zeros_array.dtype

dtype('float64')

In [11]:
#すべての要素が1
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# 空っぽのアレイ

np.empty(5)
np.empty((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# 単位行列I（dentity array）
# 5次の単位行列
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
# arange関数
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
# 5から50までで、2ずつ増分
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])